include $(GOROOT)/src/Make.inc

TARG=mongrel_raw
GOFILES=\
	mongrel_raw.go\

#if you want to try other demos, you have to switch the values above to the
#command you want to build

include $(GOROOT)/src/Make.cmd
